name: Docker Hub Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_UN }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags:  ${{ secrets.DOCKERHUB_UN }}/shokuyoku:${{ github.sha }}
